export default function TermsPage() {
  const effectiveDate = 'April 1, 2026'
  const companyName = 'Worth Fit Training'
  const appName = 'Worth Fit'
  const contactEmail = 'worthfittraining@gmail.com'
  const state = 'Kentucky'

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="max-w-3xl mx-auto px-4 py-12">
        {/* Header */}
        <div className="mb-10">
          <h1 className="text-3xl font-bold text-gray-900 mb-2">Terms & Conditions</h1>
          <p className="text-sm text-gray-500">Effective date: {effectiveDate} · Last updated: {effectiveDate}</p>
        </div>

        <div className="bg-amber-50 border border-amber-200 rounded-2xl p-4 mb-8">
          <p className="text-sm text-amber-800">
            <strong>Plain-English Summary:</strong> Worth Fit is a nutrition and fitness tracking tool — not a medical service. Nali is an AI assistant, not a doctor, dietitian, or licensed health professional. Always consult a qualified healthcare provider before making changes to your diet, exercise routine, or health plan. By using this app, you agree to these terms.
          </p>
        </div>

        <div className="space-y-8 text-gray-700">

          {/* 1 */}
          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">1. Agreement to Terms</h2>
            <p className="text-sm leading-relaxed">
              By creating an account, accessing, or using the {appName} application (the "Service") operated by {companyName} ("we," "us," or "our"), you agree to be bound by these Terms and Conditions ("Terms"). If you do not agree to these Terms, do not use the Service.
            </p>
            <p className="text-sm leading-relaxed mt-3">
              We reserve the right to update these Terms at any time. Continued use of the Service after changes are posted constitutes your acceptance of the updated Terms. We will notify users of material changes via email or an in-app notice.
            </p>
          </section>

          {/* 2 */}
          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">2. Description of Service</h2>
            <p className="text-sm leading-relaxed">
              {appName} is a personal nutrition and fitness tracking application that allows users to log food intake, track macronutrients and calories, receive AI-generated meal plans, and interact with an AI coaching assistant named Nali. The Service is provided for informational and general wellness purposes only.
            </p>
          </section>

          {/* 3 — MEDICAL DISCLAIMER */}
          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">3. Medical Disclaimer — Please Read Carefully</h2>
            <div className="bg-red-50 border border-red-200 rounded-xl p-4 space-y-3">
              <p className="text-sm leading-relaxed text-red-900">
                <strong>The Service does not provide medical advice, diagnosis, or treatment.</strong> All content, including but not limited to meal plans, calorie targets, macro recommendations, AI coaching responses, and any other information generated by or through the Service, is for general informational and educational purposes only and is not a substitute for professional medical advice, diagnosis, or treatment from a licensed physician, registered dietitian, certified nutritionist, or other qualified healthcare provider.
              </p>
              <p className="text-sm leading-relaxed text-red-900">
                <strong>Always seek the advice of a qualified healthcare professional</strong> before starting any new diet, nutrition plan, exercise program, or making any changes to your health regimen, particularly if you have or suspect a medical condition, are pregnant, nursing, or taking any medications.
              </p>
              <p className="text-sm leading-relaxed text-red-900">
                <strong>Never disregard professional medical advice or delay seeking it</strong> because of something you have read, received, or been told through the Service. If you experience any adverse effects or health concerns, stop using the Service and contact a qualified healthcare provider immediately.
              </p>
              <p className="text-sm leading-relaxed text-red-900">
                Results from using the Service vary by individual. {companyName} makes no guarantees regarding weight loss, muscle gain, improved health outcomes, athletic performance, or any other fitness or health-related result.
              </p>
            </div>
          </section>

          {/* 4 */}
          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">4. AI-Generated Content Disclaimer</h2>
            <p className="text-sm leading-relaxed">
              The Service incorporates artificial intelligence features, including an AI coaching assistant ("Nali") powered by third-party AI technology. You acknowledge and agree that:
            </p>
            <ul className="mt-3 space-y-2 text-sm">
              <li className="flex gap-2"><span className="text-gray-400 shrink-0">•</span><span>AI-generated content, including meal plans, macro estimates, food suggestions, and coaching messages, may be inaccurate, incomplete, or not appropriate for your specific circumstances.</span></li>
              <li className="flex gap-2"><span className="text-gray-400 shrink-0">•</span><span>Nali is not a licensed dietitian, nutritionist, personal trainer, physician, or any other type of healthcare professional.</span></li>
              <li className="flex gap-2"><span className="text-gray-400 shrink-0">•</span><span>AI responses should not be relied upon as professional health or medical advice.</span></li>
              <li className="flex gap-2"><span className="text-gray-400 shrink-0">•</span><span>Calorie and macro estimates provided by the Service are approximations and may not reflect the actual nutritional content of foods.</span></li>
              <li className="flex gap-2"><span className="text-gray-400 shrink-0">•</span><span>You use AI-generated content entirely at your own risk.</span></li>
            </ul>
          </section>

          {/* 5 */}
          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">5. Eligibility and User Accounts</h2>
            <p className="text-sm leading-relaxed">
              You must be at least 18 years of age to use the Service. By using the Service, you represent and warrant that you are 18 or older and have the legal capacity to enter into these Terms.
            </p>
            <p className="text-sm leading-relaxed mt-3">
              You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. You agree to notify us immediately at {contactEmail} of any unauthorized use of your account. {companyName} will not be liable for any loss or damage arising from your failure to protect your account.
            </p>
            <p className="text-sm leading-relaxed mt-3">
              You agree to provide accurate, current, and complete information when creating your account and to keep your profile information up to date. We reserve the right to suspend or terminate accounts that contain false or misleading information.
            </p>
          </section>

          {/* 6 */}
          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">6. Subscription Plans and Billing</h2>
            <p className="text-sm leading-relaxed">
              {appName} offers a free tier and paid subscription plans ("Standard" and "Premium"). Paid subscriptions are billed on a recurring basis through our third-party payment processor, Stripe. By subscribing to a paid plan, you authorize {companyName} to charge your payment method on a recurring basis at the applicable subscription rate.
            </p>
            <ul className="mt-3 space-y-2 text-sm">
              <li className="flex gap-2"><span className="text-gray-400 shrink-0">•</span><span><strong>Automatic Renewal:</strong> Subscriptions automatically renew at the end of each billing period unless cancelled before the renewal date.</span></li>
              <li className="flex gap-2"><span className="text-gray-400 shrink-0">•</span><span><strong>Price Changes:</strong> We reserve the right to change subscription prices with at least 14 days' notice via email or in-app notification. Continued use after a price change constitutes acceptance of the new pricing.</span></li>
              <li className="flex gap-2"><span className="text-gray-400 shrink-0">•</span><span><strong>Taxes:</strong> Subscription prices may be subject to applicable taxes, which will be added to your billing amount as required by law.</span></li>
              <li className="flex gap-2"><span className="text-gray-400 shrink-0">•</span><span><strong>Failed Payments:</strong> If a payment fails, we may suspend access to paid features until payment is resolved.</span></li>
            </ul>
          </section>

          {/* 7 */}
          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">7. Cancellation and Refund Policy</h2>
            <p className="text-sm leading-relaxed">
              You may cancel your subscription at any time through your account settings or by contacting us at {contactEmail}. Cancellation takes effect at the end of the current billing period, and you will retain access to paid features until that date.
            </p>
            <p className="text-sm leading-relaxed mt-3">
              <strong>Refunds:</strong> All subscription fees are non-refundable except where required by applicable law. We do not provide prorated refunds for unused portions of a subscription period. If you believe you were charged in error, contact us within 30 days of the charge at {contactEmail} and we will review your request.
            </p>
          </section>

          {/* 8 */}
          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">8. Acceptable Use</h2>
            <p className="text-sm leading-relaxed">You agree not to use the Service to:</p>
            <ul className="mt-3 space-y-2 text-sm">
              <li className="flex gap-2"><span className="text-gray-400 shrink-0">•</span><span>Violate any applicable local, state, national, or international law or regulation</span></li>
              <li className="flex gap-2"><span className="text-gray-400 shrink-0">•</span><span>Impersonate any person or entity or falsely represent your affiliation with any person or entity</span></li>
              <li className="flex gap-2"><span className="text-gray-400 shrink-0">•</span><span>Attempt to gain unauthorized access to any part of the Service or its related systems</span></li>
              <li className="flex gap-2"><span className="text-gray-400 shrink-0">•</span><span>Reverse engineer, decompile, or disassemble any part of the Service</span></li>
              <li className="flex gap-2"><span className="text-gray-400 shrink-0">•</span><span>Scrape, harvest, or collect data from the Service without our express written permission</span></li>
              <li className="flex gap-2"><span className="text-gray-400 shrink-0">•</span><span>Use the Service in any manner that could disable, overburden, or impair its functionality</span></li>
              <li className="flex gap-2"><span className="text-gray-400 shrink-0">•</span><span>Use the Service for any commercial purpose without our express written consent</span></li>
              <li className="flex gap-2"><span className="text-gray-400 shrink-0">•</span><span>Share your account credentials with others or allow multiple individuals to use a single account</span></li>
            </ul>
            <p className="text-sm leading-relaxed mt-3">
              Violation of these rules may result in immediate termination of your account without refund.
            </p>
          </section>

          {/* 9 */}
          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">9. User Data and Privacy</h2>
            <p className="text-sm leading-relaxed">
              By using the Service, you acknowledge that we collect and process personal and health-related data you provide, including but not limited to your name, email address, body measurements, dietary preferences, food logs, and fitness goals. This data is used to provide and personalize the Service.
            </p>
            <p className="text-sm leading-relaxed mt-3">
              You represent and warrant that any health or personal data you enter into the Service is accurate to the best of your knowledge. You grant {companyName} a limited license to use your data solely for the purpose of providing the Service to you.
            </p>
            <p className="text-sm leading-relaxed mt-3">
              We take reasonable technical measures to protect your data, but we cannot guarantee absolute security. You acknowledge that transmitting information over the internet carries inherent risks. {companyName} is not responsible for unauthorized access to your data that results from circumstances beyond our reasonable control.
            </p>
          </section>

          {/* 10 */}
          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">10. Intellectual Property</h2>
            <p className="text-sm leading-relaxed">
              The Service, including its design, features, content, software, and all associated intellectual property, is owned by {companyName} and is protected by applicable copyright, trademark, and other intellectual property laws. You may not copy, modify, distribute, sell, or lease any part of the Service without our express written permission.
            </p>
            <p className="text-sm leading-relaxed mt-3">
              You retain ownership of any personal data and content you input into the Service (such as your food logs and notes). By submitting content to the Service, you grant {companyName} a non-exclusive, royalty-free license to use that content solely for the purpose of operating and improving the Service.
            </p>
          </section>

          {/* 11 */}
          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">11. Third-Party Services</h2>
            <p className="text-sm leading-relaxed">
              The Service integrates with third-party services including payment processing (Stripe), authentication (Clerk), data storage (Airtable), and AI services (Anthropic). Your use of these third-party services is subject to their respective terms of service and privacy policies. {companyName} is not responsible for the acts or omissions of any third-party service provider.
            </p>
          </section>

          {/* 12 */}
          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">12. Disclaimer of Warranties</h2>
            <p className="text-sm leading-relaxed uppercase font-semibold text-gray-600">
              THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED.
            </p>
            <p className="text-sm leading-relaxed mt-3">
              To the fullest extent permitted by applicable law, {companyName} expressly disclaims all warranties, including but not limited to implied warranties of merchantability, fitness for a particular purpose, accuracy, and non-infringement. We do not warrant that:
            </p>
            <ul className="mt-3 space-y-2 text-sm">
              <li className="flex gap-2"><span className="text-gray-400 shrink-0">•</span><span>The Service will be uninterrupted, error-free, or secure</span></li>
              <li className="flex gap-2"><span className="text-gray-400 shrink-0">•</span><span>Any results obtained through the Service will be accurate, reliable, or achieve any particular health or fitness outcome</span></li>
              <li className="flex gap-2"><span className="text-gray-400 shrink-0">•</span><span>Nutritional information provided is complete or up to date</span></li>
              <li className="flex gap-2"><span className="text-gray-400 shrink-0">•</span><span>AI-generated content is appropriate, accurate, or suitable for your individual needs</span></li>
            </ul>
          </section>

          {/* 13 */}
          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">13. Limitation of Liability</h2>
            <p className="text-sm leading-relaxed uppercase font-semibold text-gray-600">
              TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, {companyName.toUpperCase()} AND ITS OWNERS, OFFICERS, EMPLOYEES, AGENTS, AND AFFILIATES SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES.
            </p>
            <p className="text-sm leading-relaxed mt-3">
              This includes, without limitation, damages for loss of profits, revenue, data, goodwill, or other intangible losses, resulting from: (i) your use of or inability to use the Service; (ii) reliance on any content or information provided through the Service; (iii) any health outcome or physical condition resulting from following advice, meal plans, or recommendations generated by the Service; (iv) unauthorized access to or alteration of your data; or (v) any other matter relating to the Service.
            </p>
            <p className="text-sm leading-relaxed mt-3">
              In no event shall {companyName}'s total liability to you for all claims arising out of or relating to the Service exceed the greater of (a) the total amount you paid to {companyName} in the twelve (12) months immediately preceding the claim, or (b) one hundred dollars ($100.00).
            </p>
            <p className="text-sm leading-relaxed mt-3">
              Some jurisdictions do not allow the exclusion or limitation of certain damages, so the above limitations may not fully apply to you.
            </p>
          </section>

          {/* 14 */}
          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">14. Indemnification</h2>
            <p className="text-sm leading-relaxed">
              You agree to defend, indemnify, and hold harmless {companyName} and its owners, officers, employees, agents, and affiliates from and against any and all claims, damages, obligations, losses, liabilities, costs, and expenses (including reasonable attorneys' fees) arising from: (i) your use of the Service; (ii) your violation of these Terms; (iii) your violation of any third-party rights; or (iv) any claim that content you submitted caused damage to a third party.
            </p>
          </section>

          {/* 15 */}
          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">15. Dispute Resolution and Binding Arbitration</h2>
            <p className="text-sm leading-relaxed">
              <strong>Please read this section carefully — it affects your legal rights.</strong>
            </p>
            <p className="text-sm leading-relaxed mt-3">
              Any dispute, claim, or controversy arising out of or relating to these Terms or the Service that cannot be resolved informally shall be resolved through final and binding arbitration, rather than in court. Arbitration shall be conducted by a single arbitrator under the rules of the American Arbitration Association (AAA) and shall take place in {state}. The arbitrator's decision shall be final and binding and may be entered as a judgment in any court of competent jurisdiction.
            </p>
            <p className="text-sm leading-relaxed mt-3">
              Before initiating arbitration, you agree to first contact us at {contactEmail} and give us 30 days to attempt to resolve the dispute informally.
            </p>
            <p className="text-sm leading-relaxed mt-3">
              <strong>Class Action Waiver:</strong> You agree that any dispute resolution proceedings will be conducted only on an individual basis and not in a class, consolidated, or representative action. You waive any right to participate in a class action lawsuit or class-wide arbitration.
            </p>
            <p className="text-sm leading-relaxed mt-3">
              You may opt out of binding arbitration within 30 days of first accepting these Terms by emailing {contactEmail} with the subject line "Arbitration Opt-Out." If you opt out, disputes will be resolved in the courts of {state}.
            </p>
          </section>

          {/* 16 */}
          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">16. Governing Law</h2>
            <p className="text-sm leading-relaxed">
              These Terms shall be governed by and construed in accordance with the laws of the Commonwealth of {state}, without regard to its conflict of law provisions. To the extent any claim is not subject to arbitration, you consent to the exclusive jurisdiction and venue of the state and federal courts located in {state}.
            </p>
          </section>

          {/* 17 */}
          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">17. Termination</h2>
            <p className="text-sm leading-relaxed">
              We reserve the right to suspend or terminate your access to the Service at any time, with or without notice, for any reason, including but not limited to violation of these Terms. Upon termination, your right to use the Service ceases immediately. Sections 3 (Medical Disclaimer), 12 (Disclaimer of Warranties), 13 (Limitation of Liability), 14 (Indemnification), and 15 (Dispute Resolution) shall survive termination.
            </p>
          </section>

          {/* 18 */}
          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">18. Miscellaneous</h2>
            <p className="text-sm leading-relaxed">
              <strong>Entire Agreement:</strong> These Terms constitute the entire agreement between you and {companyName} regarding the Service and supersede all prior agreements.
            </p>
            <p className="text-sm leading-relaxed mt-2">
              <strong>Severability:</strong> If any provision of these Terms is found to be unenforceable, the remaining provisions will remain in full force and effect.
            </p>
            <p className="text-sm leading-relaxed mt-2">
              <strong>Waiver:</strong> Our failure to enforce any provision of these Terms shall not be deemed a waiver of that provision or our right to enforce it in the future.
            </p>
            <p className="text-sm leading-relaxed mt-2">
              <strong>Assignment:</strong> You may not assign your rights or obligations under these Terms without our prior written consent. We may assign our rights and obligations without restriction.
            </p>
          </section>

          {/* 19 */}
          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">19. Contact Us</h2>
            <p className="text-sm leading-relaxed">
              If you have questions about these Terms, please contact us at:
            </p>
            <div className="mt-3 bg-gray-100 rounded-xl p-4 text-sm">
              <p className="font-semibold text-gray-800">{companyName}</p>
              <p className="text-gray-600 mt-1">Email: <a href={`mailto:${contactEmail}`} className="text-green-600 hover:underline">{contactEmail}</a></p>
              <p className="text-gray-500 mt-1 text-xs">We aim to respond to all inquiries within 3 business days.</p>
            </div>
          </section>

          {/* Legal note */}
          <div className="border-t border-gray-200 pt-6">
            <p className="text-xs text-gray-400 leading-relaxed">
              <strong>Note for Worth Fit Training:</strong> These Terms were generated to provide a strong starting point for legal protection. We strongly recommend having a licensed attorney in the Commonwealth of Kentucky review these Terms before or shortly after launching your paid subscription tiers. An attorney familiar with health app regulations, HIPAA applicability, and FTC guidelines for health claims can ensure your Terms fully protect your business.
            </p>
          </div>

        </div>
      </div>
    </div>
  )
}
